### ISSUE TITLE
KeyError: 'reference_bases' (when getting data from the progenetix website)

### ISSUE THREAD

**Issue by ClmtHua** [progenetix/bycon#20]
Hello, 

I have troubles to get ".pgxseg" files from both the R package and the website. The table I download from the website always has this python error referring the "bycon" package : 
```
Traceback (most recent call last):
  File "/Library/WebServer/cgi-bin/bycon/beaconServer/beacon.py", line 19, in main
    beacon()
  File "/Library/WebServer/cgi-bin/bycon/beaconServer/beacon.py", line 65, in beacon
    beacon_data_pipeline(byc, f)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/service_utils.py", line 59, in beacon_data_pipeline
    run_result_sets_beacon(byc)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/service_utils.py", line 287, in run_result_sets_beacon
    check_alternative_single_set_deliveries(ds_id, r_s_res, byc)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/service_utils.py", line 355, in check_alternative_single_set_deliveries
    check_alternative_variant_deliveries(ds_id, byc)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/service_utils.py", line 744, in check_alternative_variant_deliveries
    export_pgxseg_download(ds_id, byc)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/export_file_generation.py", line 165, in export_pgxseg_download
    print_variant_pgxseg(v, byc)
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/export_file_generation.py", line 173, in print_variant_pgxseg
    print( pgxseg_variant_line(v, byc) )
  File "/usr/local/lib/python3.10/site-packages/bycon/lib/export_file_generation.py", line 203, in pgxseg_variant_line
    pv["reference_bases"],
KeyError: 'reference_bases'
```

It may be linked with the recent update since I did not had these issues on Friday ?

Thanks a lot for your great tool and your help !

**Comment by mbaudis** [comment]
Thanks for the note! Should be addressed in https://github.com/progenetix/bycon/commit/0a3be945544fabfc49aab99f15ec3d63ca1e8ef4

This new bug affected the `&output=pgxseg` & `&output=datatable` options for genomic variants; `&output=vcf` was fine since the changes had been geared towards this `╮(╯▽╰)╭`
